package com.yutian.base.database.srcgen;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        MYBUYDao.createTable(db, ifNotExists);
        MYSSQDATADao.createTable(db, ifNotExists);
        MYWINDao.createTable(db, ifNotExists);
        PRICELEVELDao.createTable(db, ifNotExists);
        SSQCONFIGDao.createTable(db, ifNotExists);
        SSQNUMBERWINNERDao.createTable(db, ifNotExists);
        SSQPERIODDATADao.createTable(db, ifNotExists);
        SSQPERIODSTATUSDao.createTable(db, ifNotExists);
        SSQTIMEINFORDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        MYBUYDao.dropTable(db, ifExists);
        MYSSQDATADao.dropTable(db, ifExists);
        MYWINDao.dropTable(db, ifExists);
        PRICELEVELDao.dropTable(db, ifExists);
        SSQCONFIGDao.dropTable(db, ifExists);
        SSQNUMBERWINNERDao.dropTable(db, ifExists);
        SSQPERIODDATADao.dropTable(db, ifExists);
        SSQPERIODSTATUSDao.dropTable(db, ifExists);
        SSQTIMEINFORDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, true);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(MYBUYDao.class);
        registerDaoClass(MYSSQDATADao.class);
        registerDaoClass(MYWINDao.class);
        registerDaoClass(PRICELEVELDao.class);
        registerDaoClass(SSQCONFIGDao.class);
        registerDaoClass(SSQNUMBERWINNERDao.class);
        registerDaoClass(SSQPERIODDATADao.class);
        registerDaoClass(SSQPERIODSTATUSDao.class);
        registerDaoClass(SSQTIMEINFORDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
