package com.yutian.base.database.srcgen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mYBUYDaoConfig;
    private final DaoConfig mYSSQDATADaoConfig;
    private final DaoConfig mYWINDaoConfig;
    private final DaoConfig pRICELEVELDaoConfig;
    private final DaoConfig sSQCONFIGDaoConfig;
    private final DaoConfig sSQNUMBERWINNERDaoConfig;
    private final DaoConfig sSQPERIODDATADaoConfig;
    private final DaoConfig sSQPERIODSTATUSDaoConfig;
    private final DaoConfig sSQTIMEINFORDaoConfig;

    private final MYBUYDao mYBUYDao;
    private final MYSSQDATADao mYSSQDATADao;
    private final MYWINDao mYWINDao;
    private final PRICELEVELDao pRICELEVELDao;
    private final SSQCONFIGDao sSQCONFIGDao;
    private final SSQNUMBERWINNERDao sSQNUMBERWINNERDao;
    private final SSQPERIODDATADao sSQPERIODDATADao;
    private final SSQPERIODSTATUSDao sSQPERIODSTATUSDao;
    private final SSQTIMEINFORDao sSQTIMEINFORDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mYBUYDaoConfig = daoConfigMap.get(MYBUYDao.class).clone();
        mYBUYDaoConfig.initIdentityScope(type);

        mYSSQDATADaoConfig = daoConfigMap.get(MYSSQDATADao.class).clone();
        mYSSQDATADaoConfig.initIdentityScope(type);

        mYWINDaoConfig = daoConfigMap.get(MYWINDao.class).clone();
        mYWINDaoConfig.initIdentityScope(type);

        pRICELEVELDaoConfig = daoConfigMap.get(PRICELEVELDao.class).clone();
        pRICELEVELDaoConfig.initIdentityScope(type);

        sSQCONFIGDaoConfig = daoConfigMap.get(SSQCONFIGDao.class).clone();
        sSQCONFIGDaoConfig.initIdentityScope(type);

        sSQNUMBERWINNERDaoConfig = daoConfigMap.get(SSQNUMBERWINNERDao.class).clone();
        sSQNUMBERWINNERDaoConfig.initIdentityScope(type);

        sSQPERIODDATADaoConfig = daoConfigMap.get(SSQPERIODDATADao.class).clone();
        sSQPERIODDATADaoConfig.initIdentityScope(type);

        sSQPERIODSTATUSDaoConfig = daoConfigMap.get(SSQPERIODSTATUSDao.class).clone();
        sSQPERIODSTATUSDaoConfig.initIdentityScope(type);

        sSQTIMEINFORDaoConfig = daoConfigMap.get(SSQTIMEINFORDao.class).clone();
        sSQTIMEINFORDaoConfig.initIdentityScope(type);

        mYBUYDao = new MYBUYDao(mYBUYDaoConfig, this);
        mYSSQDATADao = new MYSSQDATADao(mYSSQDATADaoConfig, this);
        mYWINDao = new MYWINDao(mYWINDaoConfig, this);
        pRICELEVELDao = new PRICELEVELDao(pRICELEVELDaoConfig, this);
        sSQCONFIGDao = new SSQCONFIGDao(sSQCONFIGDaoConfig, this);
        sSQNUMBERWINNERDao = new SSQNUMBERWINNERDao(sSQNUMBERWINNERDaoConfig, this);
        sSQPERIODDATADao = new SSQPERIODDATADao(sSQPERIODDATADaoConfig, this);
        sSQPERIODSTATUSDao = new SSQPERIODSTATUSDao(sSQPERIODSTATUSDaoConfig, this);
        sSQTIMEINFORDao = new SSQTIMEINFORDao(sSQTIMEINFORDaoConfig, this);

        registerDao(MYBUY.class, mYBUYDao);
        registerDao(MYSSQDATA.class, mYSSQDATADao);
        registerDao(MYWIN.class, mYWINDao);
        registerDao(PRICELEVEL.class, pRICELEVELDao);
        registerDao(SSQCONFIG.class, sSQCONFIGDao);
        registerDao(SSQNUMBERWINNER.class, sSQNUMBERWINNERDao);
        registerDao(SSQPERIODDATA.class, sSQPERIODDATADao);
        registerDao(SSQPERIODSTATUS.class, sSQPERIODSTATUSDao);
        registerDao(SSQTIMEINFOR.class, sSQTIMEINFORDao);
    }
    
    public void clear() {
        mYBUYDaoConfig.getIdentityScope().clear();
        mYSSQDATADaoConfig.getIdentityScope().clear();
        mYWINDaoConfig.getIdentityScope().clear();
        pRICELEVELDaoConfig.getIdentityScope().clear();
        sSQCONFIGDaoConfig.getIdentityScope().clear();
        sSQNUMBERWINNERDaoConfig.getIdentityScope().clear();
        sSQPERIODDATADaoConfig.getIdentityScope().clear();
        sSQPERIODSTATUSDaoConfig.getIdentityScope().clear();
        sSQTIMEINFORDaoConfig.getIdentityScope().clear();
    }

    public MYBUYDao getMYBUYDao() {
        return mYBUYDao;
    }

    public MYSSQDATADao getMYSSQDATADao() {
        return mYSSQDATADao;
    }

    public MYWINDao getMYWINDao() {
        return mYWINDao;
    }

    public PRICELEVELDao getPRICELEVELDao() {
        return pRICELEVELDao;
    }

    public SSQCONFIGDao getSSQCONFIGDao() {
        return sSQCONFIGDao;
    }

    public SSQNUMBERWINNERDao getSSQNUMBERWINNERDao() {
        return sSQNUMBERWINNERDao;
    }

    public SSQPERIODDATADao getSSQPERIODDATADao() {
        return sSQPERIODDATADao;
    }

    public SSQPERIODSTATUSDao getSSQPERIODSTATUSDao() {
        return sSQPERIODSTATUSDao;
    }

    public SSQTIMEINFORDao getSSQTIMEINFORDao() {
        return sSQTIMEINFORDao;
    }

}
