package com.yutian.base.database.srcgen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MYBUY".
 */
public class MYBUY {

    /** Not-null value. */
    private String ID;
    private int NUMBER;
    /** Not-null value. */
    private java.util.Date ADDTIME;
    /** Not-null value. */
    private String PERIOD;

    public MYBUY() {
    }

    public MYBUY(String ID, String PERIOD) {
        this.ID = ID;
        this.PERIOD = PERIOD;
    }

    public MYBUY(String ID, int NUMBER, java.util.Date ADDTIME, String PERIOD) {
        this.ID = ID;
        this.NUMBER = NUMBER;
        this.ADDTIME = ADDTIME;
        this.PERIOD = PERIOD;
    }

    /** Not-null value. */
    public String getID() {
        return ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setID(String ID) {
        this.ID = ID;
    }

    public int getNUMBER() {
        return NUMBER;
    }

    public void setNUMBER(int NUMBER) {
        this.NUMBER = NUMBER;
    }

    /** Not-null value. */
    public java.util.Date getADDTIME() {
        return ADDTIME;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setADDTIME(java.util.Date ADDTIME) {
        this.ADDTIME = ADDTIME;
    }

    /** Not-null value. */
    public String getPERIOD() {
        return PERIOD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPERIOD(String PERIOD) {
        this.PERIOD = PERIOD;
    }

}
