package com.yutian.base.database.srcgen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MYSSQDATA".
 */
public class MYSSQDATA {

    private String ID;
    private Integer NUMBER;
    private String RED1;
    private String RED2;
    private String RED3;
    private String RED4;
    private String RED5;
    private String RED6;
    private String BLUE;
    private String REDBALL;
    private String BLUEBALL;
    private Integer COUNT;

    public MYSSQDATA() {
    }

    public MYSSQDATA(String ID, Integer NUMBER) {
        this.ID = ID;
        this.NUMBER = NUMBER;
    }

    public MYSSQDATA(String ID, Integer NUMBER, String RED1, String RED2, String RED3, String RED4, String RED5, String RED6, String BLUE, String REDBALL, String BLUEBALL, Integer COUNT) {
        this.ID = ID;
        this.NUMBER = NUMBER;
        this.RED1 = RED1;
        this.RED2 = RED2;
        this.RED3 = RED3;
        this.RED4 = RED4;
        this.RED5 = RED5;
        this.RED6 = RED6;
        this.BLUE = BLUE;
        this.REDBALL = REDBALL;
        this.BLUEBALL = BLUEBALL;
        this.COUNT = COUNT;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public Integer getNUMBER() {
        return NUMBER;
    }

    public void setNUMBER(Integer NUMBER) {
        this.NUMBER = NUMBER;
    }

    public String getRED1() {
        return RED1;
    }

    public void setRED1(String RED1) {
        this.RED1 = RED1;
    }

    public String getRED2() {
        return RED2;
    }

    public void setRED2(String RED2) {
        this.RED2 = RED2;
    }

    public String getRED3() {
        return RED3;
    }

    public void setRED3(String RED3) {
        this.RED3 = RED3;
    }

    public String getRED4() {
        return RED4;
    }

    public void setRED4(String RED4) {
        this.RED4 = RED4;
    }

    public String getRED5() {
        return RED5;
    }

    public void setRED5(String RED5) {
        this.RED5 = RED5;
    }

    public String getRED6() {
        return RED6;
    }

    public void setRED6(String RED6) {
        this.RED6 = RED6;
    }

    public String getBLUE() {
        return BLUE;
    }

    public void setBLUE(String BLUE) {
        this.BLUE = BLUE;
    }

    public String getREDBALL() {
        return REDBALL;
    }

    public void setREDBALL(String REDBALL) {
        this.REDBALL = REDBALL;
    }

    public String getBLUEBALL() {
        return BLUEBALL;
    }

    public void setBLUEBALL(String BLUEBALL) {
        this.BLUEBALL = BLUEBALL;
    }

    public Integer getCOUNT() {
        return COUNT;
    }

    public void setCOUNT(Integer COUNT) {
        this.COUNT = COUNT;
    }

}
