package com.yutian.base.database.srcgen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MYWIN".
 */
public class MYWIN {

    private String ID;
    private Integer NUMBER;
    private Integer PRICELEVEL;
    private String PRICEVAL;
    private String PERIOD;

    public MYWIN() {
    }

    public MYWIN(String ID, Integer NUMBER, String PERIOD) {
        this.ID = ID;
        this.NUMBER = NUMBER;
        this.PERIOD = PERIOD;
    }

    public MYWIN(String ID, Integer NUMBER, Integer PRICELEVEL, String PRICEVAL, String PERIOD) {
        this.ID = ID;
        this.NUMBER = NUMBER;
        this.PRICELEVEL = PRICELEVEL;
        this.PRICEVAL = PRICEVAL;
        this.PERIOD = PERIOD;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public Integer getNUMBER() {
        return NUMBER;
    }

    public void setNUMBER(Integer NUMBER) {
        this.NUMBER = NUMBER;
    }

    public Integer getPRICELEVEL() {
        return PRICELEVEL;
    }

    public void setPRICELEVEL(Integer PRICELEVEL) {
        this.PRICELEVEL = PRICELEVEL;
    }

    public String getPRICEVAL() {
        return PRICEVAL;
    }

    public void setPRICEVAL(String PRICEVAL) {
        this.PRICEVAL = PRICEVAL;
    }

    public String getPERIOD() {
        return PERIOD;
    }

    public void setPERIOD(String PERIOD) {
        this.PERIOD = PERIOD;
    }

}
