package com.yutian.base.database.srcgen;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MYWIN".
*/
public class MYWINDao extends AbstractDao<MYWIN, Void> {

    public static final String TABLENAME = "MYWIN";

    /**
     * Properties of entity MYWIN.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ID = new Property(0, String.class, "ID", true, "ID");
        public final static Property NUMBER = new Property(1, Integer.class, "NUMBER", true, "NUMBER");
        public final static Property PRICELEVEL = new Property(2, Integer.class, "PRICELEVEL", false, "PRICELEVEL");
        public final static Property PRICEVAL = new Property(3, String.class, "PRICEVAL", false, "PRICEVAL");
        public final static Property PERIOD = new Property(4, String.class, "PERIOD", true, "PERIOD");
    };


    public MYWINDao(DaoConfig config) {
        super(config);
    }
    
    public MYWINDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MYWIN\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: ID
                "\"NUMBER\" INTEGER PRIMARY KEY ," + // 1: NUMBER
                "\"PRICELEVEL\" INTEGER," + // 2: PRICELEVEL
                "\"PRICEVAL\" TEXT," + // 3: PRICEVAL
                "\"PERIOD\" TEXT PRIMARY KEY NOT NULL );"); // 4: PERIOD
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MYWIN\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MYWIN entity) {
        stmt.clearBindings();
 
        String ID = entity.getID();
        if (ID != null) {
            stmt.bindString(1, ID);
        }
 
        Integer NUMBER = entity.getNUMBER();
        if (NUMBER != null) {
            stmt.bindLong(2, NUMBER);
        }
 
        Integer PRICELEVEL = entity.getPRICELEVEL();
        if (PRICELEVEL != null) {
            stmt.bindLong(3, PRICELEVEL);
        }
 
        String PRICEVAL = entity.getPRICEVAL();
        if (PRICEVAL != null) {
            stmt.bindString(4, PRICEVAL);
        }
 
        String PERIOD = entity.getPERIOD();
        if (PERIOD != null) {
            stmt.bindString(5, PERIOD);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public MYWIN readEntity(Cursor cursor, int offset) {
        MYWIN entity = new MYWIN( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // ID
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // NUMBER
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // PRICELEVEL
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // PRICEVAL
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // PERIOD
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MYWIN entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNUMBER(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setPRICELEVEL(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setPRICEVAL(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPERIOD(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(MYWIN entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(MYWIN entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
