package com.yutian.base.database.srcgen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SSQCONFIG".
 */
public class SSQCONFIG {

    private Integer ID;
    private String NAME;
    private String VALUE;

    public SSQCONFIG() {
    }

    public SSQCONFIG(Integer ID) {
        this.ID = ID;
    }

    public SSQCONFIG(Integer ID, String NAME, String VALUE) {
        this.ID = ID;
        this.NAME = NAME;
        this.VALUE = VALUE;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    public String getNAME() {
        return NAME;
    }

    public void setNAME(String NAME) {
        this.NAME = NAME;
    }

    public String getVALUE() {
        return VALUE;
    }

    public void setVALUE(String VALUE) {
        this.VALUE = VALUE;
    }

}
