package com.yutian.base.database.srcgen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SSQNUMBERWINNER".
 */
public class SSQNUMBERWINNER {

    private String PERIOD;
    private Integer PRICELEVEL;
    private String PRICEVAL;
    private String PRICENUM;

    public SSQNUMBERWINNER() {
    }

    public SSQNUMBERWINNER(String PERIOD) {
        this.PERIOD = PERIOD;
    }

    public SSQNUMBERWINNER(String PERIOD, Integer PRICELEVEL, String PRICEVAL, String PRICENUM) {
        this.PERIOD = PERIOD;
        this.PRICELEVEL = PRICELEVEL;
        this.PRICEVAL = PRICEVAL;
        this.PRICENUM = PRICENUM;
    }

    public String getPERIOD() {
        return PERIOD;
    }

    public void setPERIOD(String PERIOD) {
        this.PERIOD = PERIOD;
    }

    public Integer getPRICELEVEL() {
        return PRICELEVEL;
    }

    public void setPRICELEVEL(Integer PRICELEVEL) {
        this.PRICELEVEL = PRICELEVEL;
    }

    public String getPRICEVAL() {
        return PRICEVAL;
    }

    public void setPRICEVAL(String PRICEVAL) {
        this.PRICEVAL = PRICEVAL;
    }

    public String getPRICENUM() {
        return PRICENUM;
    }

    public void setPRICENUM(String PRICENUM) {
        this.PRICENUM = PRICENUM;
    }

}
