package com.yutian.base.database.srcgen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SSQPERIODSTATUS".
 */
public class SSQPERIODSTATUS {

    private String PERIOD;
    private String STATUS;

    public SSQPERIODSTATUS() {
    }

    public SSQPERIODSTATUS(String PERIOD) {
        this.PERIOD = PERIOD;
    }

    public SSQPERIODSTATUS(String PERIOD, String STATUS) {
        this.PERIOD = PERIOD;
        this.STATUS = STATUS;
    }

    public String getPERIOD() {
        return PERIOD;
    }

    public void setPERIOD(String PERIOD) {
        this.PERIOD = PERIOD;
    }

    public String getSTATUS() {
        return STATUS;
    }

    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS;
    }

}
