package com.yutian.base.database.srcgen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SSQTIMEINFOR".
 */
public class SSQTIMEINFOR {

    private String PERIOD;
    private java.util.Date LOTTERYTIME;
    private java.util.Date ENDTIME;
    private java.util.Date PERIODSELL;
    private java.util.Date CURRENPOOL;

    public SSQTIMEINFOR() {
    }

    public SSQTIMEINFOR(String PERIOD) {
        this.PERIOD = PERIOD;
    }

    public SSQTIMEINFOR(String PERIOD, java.util.Date LOTTERYTIME, java.util.Date ENDTIME, java.util.Date PERIODSELL, java.util.Date CURRENPOOL) {
        this.PERIOD = PERIOD;
        this.LOTTERYTIME = LOTTERYTIME;
        this.ENDTIME = ENDTIME;
        this.PERIODSELL = PERIODSELL;
        this.CURRENPOOL = CURRENPOOL;
    }

    public String getPERIOD() {
        return PERIOD;
    }

    public void setPERIOD(String PERIOD) {
        this.PERIOD = PERIOD;
    }

    public java.util.Date getLOTTERYTIME() {
        return LOTTERYTIME;
    }

    public void setLOTTERYTIME(java.util.Date LOTTERYTIME) {
        this.LOTTERYTIME = LOTTERYTIME;
    }

    public java.util.Date getENDTIME() {
        return ENDTIME;
    }

    public void setENDTIME(java.util.Date ENDTIME) {
        this.ENDTIME = ENDTIME;
    }

    public java.util.Date getPERIODSELL() {
        return PERIODSELL;
    }

    public void setPERIODSELL(java.util.Date PERIODSELL) {
        this.PERIODSELL = PERIODSELL;
    }

    public java.util.Date getCURRENPOOL() {
        return CURRENPOOL;
    }

    public void setCURRENPOOL(java.util.Date CURRENPOOL) {
        this.CURRENPOOL = CURRENPOOL;
    }

}
