package com.yutian.mtkviewer.dbcontrol.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig treeItemDaoConfig;
    private final DaoConfig fARITEMDaoConfig;

    private final TreeItemDao treeItemDao;
    private final FARITEMDao fARITEMDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        treeItemDaoConfig = daoConfigMap.get(TreeItemDao.class).clone();
        treeItemDaoConfig.initIdentityScope(type);

        fARITEMDaoConfig = daoConfigMap.get(FARITEMDao.class).clone();
        fARITEMDaoConfig.initIdentityScope(type);

        treeItemDao = new TreeItemDao(treeItemDaoConfig, this);
        fARITEMDao = new FARITEMDao(fARITEMDaoConfig, this);

        registerDao(TreeItem.class, treeItemDao);
        registerDao(FARITEM.class, fARITEMDao);
    }
    
    public void clear() {
        treeItemDaoConfig.getIdentityScope().clear();
        fARITEMDaoConfig.getIdentityScope().clear();
    }

    public TreeItemDao getTreeItemDao() {
        return treeItemDao;
    }

    public FARITEMDao getFARITEMDao() {
        return fARITEMDao;
    }

}
