package com.yutian.mtkviewer.dbcontrol.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TREE_ITEM".
 */
public class TreeItem {

    private String NAME;
    private String FARID_PARENT;
    /** Not-null value. */
    private String FARID;
    private String URL;
    private String HASGRAP;
    private String TOP_PARENT;

    public TreeItem() {
    }

    public TreeItem(String NAME, String FARID_PARENT, String FARID, String URL, String HASGRAP, String TOP_PARENT) {
        this.NAME = NAME;
        this.FARID_PARENT = FARID_PARENT;
        this.FARID = FARID;
        this.URL = URL;
        this.HASGRAP = HASGRAP;
        this.TOP_PARENT = TOP_PARENT;
    }

    public String getNAME() {
        return NAME;
    }

    public void setNAME(String NAME) {
        this.NAME = NAME;
    }

    public String getFARID_PARENT() {
        return FARID_PARENT;
    }

    public void setFARID_PARENT(String FARID_PARENT) {
        this.FARID_PARENT = FARID_PARENT;
    }

    /** Not-null value. */
    public String getFARID() {
        return FARID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFARID(String FARID) {
        this.FARID = FARID;
    }

    public String getURL() {
        return URL;
    }

    public void setURL(String URL) {
        this.URL = URL;
    }

    public String getHASGRAP() {
        return HASGRAP;
    }

    public void setHASGRAP(String HASGRAP) {
        this.HASGRAP = HASGRAP;
    }

    public String getTOP_PARENT() {
        return TOP_PARENT;
    }

    public void setTOP_PARENT(String TOP_PARENT) {
        this.TOP_PARENT = TOP_PARENT;
    }

}
